#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

QUEUE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/msmtp/queue"
LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/msmtp/"
LOG_FILE="${LOG_DIR}/queue.log"

mkdir -p "$LOG_DIR"

# Copy the original STDOUT so we can write output.
exec {stdout}>&1
msg() {
    echo "$(date -Iseconds) $1" >&$stdout
}

# Redirect stdout to a log, and add dates/times to each line.
exec > >(while read -r line; do
             echo "$(date -Iseconds) $line"
         done >>"${LOG_FILE}") 2>&1

# Wait to finish logging on exit.
bail() {
    exec 1>&- 2>&-
    wait
}
trap bail EXIT

lock() {
    local lock_fd
    local path="${!#}"
    exec {lock_fd}<"$path"
    flock "$lock_fd"
}

# Anything to do?
DIRS=("$QUEUE_DIR"/*.mail/)
if [[ ${#DIRS} -eq 0 ]]; then
    exit 0
fi
unset DIRS # Recompute this later as it can change (look ma, no locks!)...

if [[ ! -w "$QUEUE_DIR" ]]; then
    echo "Insufficient privileges to write to queue."
    exit 1
fi

if ! lock -n -x "$QUEUE_DIR"; then
    msg "Already running..."
    exit 0
fi

for mail in "$QUEUE_DIR"/*.mail/; do
    id="$(basename "$mail")"
    prefix="mail [ $id ]"
    if [[ ! -r "$mail/msmtp_flags" ]]; then
        echo "$prefix failed to send message; missing flags"
        continue
    fi
    if [[ ! -r "$mail/message" ]]; then
        echo "$prefix failed to send message; missing message"
        continue
    fi

    if [[ ! -w "$mail" ]]; then
        echo "$prefix failed to send message; insufficient privileges"
        continue
    fi

    prefix="$prefix [ $(xargs -0 -a "$mail/msmtp_flags" printf '%s ')]"

    echo "$prefix sending"
    xargs -0 -a "$mail/msmtp_flags" msmtp -X - < "$mail/message"
    ret="$?"
    if [[ ! "$ret" -eq 0 ]] ; then
        echo "$prefix failed to send; msmtp rc = $ret"
        continue
    fi
    if ! rm -rf "$mail"; then
        echo "$prefix sent but not purged from queue!?"
    fi
done
